services:
  nginx:
    image: nginx:1.28.0
    ports:
      - "4001:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    depends_on:
      - php

  php:
    image: php:8.3.22-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mysql_data:
